# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Basic Analysis Grocery App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"

      - name: Setting up configuration
        run: |
          flutter pub get
          flutter doctor -v

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
